version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
